variables:
  global_cycle_seconds: 1e-9 # 1 / 0.7 GHz = 1.43 ns
  technology: "45nm"

architecture:
  version: 0.4
  nodes:
  - !Component
    name: MainMemory
    class: DRAM
    attributes: {width: 3200, word_bits: 16, datawidth: 16, shared_bandwidth: 200}
    required_actions: ['read', 'write']
  - !Component
    name: GlobalBuffer
    class: SRAM 
    attributes:  {depth: 65536, width: 4096, block_size: 256, word_bits: 16, datawidth: 16, n_rdwr_ports: 4, shared_bandwidth: 4000 }
    required_actions: ['read', 'write']
  - !Container
    name: PE
    spatial:
      meshX: 256
      meshY: 256
  - !Component
    name: PEWeightStorage
    class: regfile
    attributes: { depth: 16, datawidth: 16, width: 16, n_rdwr_ports: 4}
    required_actions: ['read', 'write']
  - !Component
    name: MACC
    class: fpmac
    attributes: 
       datawidth: 16
       width: 16
       cycle_time: 1e-9
    required_actions: ['compute']



